# Generated by Django 6.0.1 on 2026-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="message",
            field=models.TextField(max_length=2000),
        ),
    ]
